# Generated by Django 4.1.3 on 2022-12-02 06:46

from django.db import migrations, models
import projectapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('projectapp', '0003_alter_video_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='preview',
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.ImageField(default='videos/default.jpg', upload_to=projectapp.models.upload_to, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
